### ISSUE TITLE
PayoutMethodsApi.java:238-240: The Stripe refreshUrl and...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#100]
The puzzle `91-67621134` from #91 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/09e62f5da2b6425e24fcf467d022ee4579b4fab2/src/main/java/com/selfxdsd/selfweb/api/PayoutMethodsApi.java#L238-L240

The puzzle was created by @amihaiemil on 18-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this

**Comment by criske** [comment]
@amihaiemil
Btw no bounty needed, it looks like is a small fix

**Comment by amihaiemil** [comment]
paid with transaction id 5Y312178YN6690821

**Comment by 0pdd** [comment]
The puzzle `91-67621134` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
