### ISSUE TITLE
Misplaced Arrow in Avatar Drop-Down

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#102]
On the upper right-hand side of the page, when you click on the user's avatar, a drop-down appears which contains an unwanted arrow.

This arrow should be removed.

<img width="231" alt="Screenshot 2020-09-23 at 11 34 13" src="https://user-images.githubusercontent.com/6305156/93988017-ec4feb80-fd90-11ea-809b-1cf16d7d1fbc.png">

**Comment by criske** [comment]
@amihaiemil I'll work on this

**Comment by amihaiemil** [comment]
paid with transaction id 40B89910FL8721424

**Comment by amihaiemil** [comment]
@criske thanks!
