### ISSUE TITLE
Rename DB env Variables

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#105]
Seems like we cannot set env variables which have dots in their names. Let's rename them to
``self_db_user``, ``self_db_password`` and ``self_db_url``.

We should also rename the stripe token variable.

**Comment by amihaiemil** [comment]
@criske FYI

**Comment by criske** [comment]
@amihaiemil any idea why this happens? On local works

**Comment by amihaiemil** [comment]
@criske I'm working to set up a test environment (we are almost done with self-pm so we can out it to work).

Apparently, you can't have dots in the env variable names on linux :)
