### ISSUE TITLE
Org Repos Tab: Make the repo names Links

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#127]
Similarly to how it's done in [getPublicRepos.js](https://github.com/self-xdsd/self-web/blob/master/src/main/resources/public/js/getPublicRepos.js#L23), we should make the org repos display as links as well.

In method [getRepoAsTableRow](https://github.com/self-xdsd/self-web/blob/master/src/main/resources/public/js/getOrgRepos.js#L40) we should wrap the name inside ``<a>`` tags, with a ``href`` pointing to ``/github/{repoFullName}``.

**Comment by Lumi3011** [comment]
If I understand well, the method should look like this? 

![image](https://user-images.githubusercontent.com/32979820/95090216-b0703b00-072d-11eb-81f7-8e709f7d857b.png)

**Comment by amihaiemil** [comment]
@Lumi3011 yep :D

**Comment by Lumi3011** [comment]
@amihaiemil ok then, it's done, i'll make a push with the changes.

**Comment by amihaiemil** [comment]
paid with transaction id 7LY03234N8855251U
