### ISSUE TITLE
Sticky Footer Hides Content

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#129]
Seems like the footer hides the content at the bottom of the page.

![Screenshot_2020-10-05 Self XDSD](https://user-images.githubusercontent.com/6305156/95098646-9fc4c280-0737-11eb-83dd-b4cbfa137447.png)

This seems to happen on all the pages.

The problem might be related to the main content element (which is usually ``<article>``), maybe it does not have the required CSS classes :D 

Some SO Question that might be useful: https://stackoverflow.com/questions/13881548/sticky-footer-hiding-content

**Comment by amihaiemil** [comment]
@Lumi3011 Can you have a look when you have some time? :D 

I remember I also had this issue when I tried to make the sticky footer.

**Comment by amihaiemil** [comment]
@Lumi3011 It also happens on the home page: 

![Screenshot_2020-10-05 Self XDSD(1)](https://user-images.githubusercontent.com/6305156/95099173-3f825080-0738-11eb-88ae-ab3d74851862.png)

I'm not sure, but I think it's the relation between the main content element and the footer. The footer should be at the end of the content, not over it -- if the content is longer than the current screen, the footer should not be visible until the user scrolls down to the end of the page.

**Comment by Lumi3011** [comment]
Sure, I will look into it, I only checked on my user page, where it was a liitle content and i didn't saw that.

**Comment by amihaiemil** [comment]
@Lumi3011 no problem :D

**Comment by Lumi3011** [comment]
@amihaiemil Done. I set the footer position absolute, to be down on every page, then I added some padding to the body, the same as the footer size, so it will be displayed properly.

**Comment by amihaiemil** [comment]
paid with transaction id 1PJ20271J9508625Y

**Comment by amihaiemil** [comment]
@Lumi3011 Thanks!

**Comment by Lumi3011** [comment]
@amihaiemil thank you too!
