### ISSUE TITLE
Home Page Responsiveness Bug

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#132]
Currently the text sections (What is Self, Register your repository etc) are not displaying well on mobile. 

![Screenshot_2020-10-07 Self XDSD](https://user-images.githubusercontent.com/6305156/95314066-83409b80-0899-11eb-8030-4428403212a9.png)

On mobile, they should be one after the other and the images should not be displayed.

**Comment by amihaiemil** [comment]
@Lumi3011 Can you please have a look here when you have some time? :D

**Comment by amihaiemil** [comment]
@Lumi3011 The page was made after this example: https://getbootstrap.com/docs/4.0/examples/product/
There's most likely a problem with the Bootstrap classes being used on the elements :D

**Comment by Lumi3011** [comment]
@amihaiemil None of the images should be seen on mobile? Neither the first image on the page?

**Comment by amihaiemil** [comment]
@Lumi3011 The first one should stay. The ones from left and right of the paragraphs (what it is, register your repo...) should not be visible :D

**Comment by Lumi3011** [comment]
@amihaiemil I have solved it. I had to add some classes in the html file to add style based on them. The responsiveness problem occurs because of a bootstrap class "w-50". I tried to delete it at first, but then I've got some bugs on desktop, so the preferred solution was to create a media query for mobile.

**Comment by amihaiemil** [comment]
paid with transaction id 04234441TN3636458

**Comment by Lumi3011** [comment]
Thank you!
