### ISSUE TITLE
WalletsApi.java:46-47: Add an endpoint and front-end code...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#137]
The puzzle `135-6e71764e` from #135 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/07f9e50782905536fc3b2c8bbead1f40756ac974/src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java#L46-L47

The puzzle was created by @amihaiemil on 11-Oct-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this, I think we have activation available in stroage.

**Comment by amihaiemil** [comment]
@criske dont work on it yet, I already have a branch with a lot of changes in that area, so we will have a lot of conflicts :)

**Comment by amihaiemil** [comment]
@criske actually, you can do it, but only the backend, no frontend yet please.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-25T10:00:30.993419``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
paid with transaction id 4R464596P64562947

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
