### ISSUE TITLE
WalletsApi.java:48-50: Once the PaymentMethod logic is...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#138]
The puzzle `135-163bde02` from #135 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/07f9e50782905536fc3b2c8bbead1f40756ac974/src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java#L48-L50

The puzzle was created by @amihaiemil on 11-Oct-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
