### ISSUE TITLE
WalletsApi.java:51-53: Once the Wallet.updateCash(...)...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#139]
The puzzle `135-26d24fff` from #135 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/07f9e50782905536fc3b2c8bbead1f40756ac974/src/main/java/com/selfxdsd/selfweb/api/WalletsApi.java#L51-L53

The puzzle was created by @amihaiemil on 11-Oct-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske I'm pretty sure we already have this implemented. Just update the core and storage versions to the latest.

**Comment by amihaiemil** [comment]
paid with transaction id 26A27025WM7411816

**Comment by 0pdd** [comment]
The puzzle `135-26d24fff` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
