### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#14]
We need CSS Styling for the HTML. First, we should come up with a good design, then implement it.

**Comment by amihaiemil** [comment]
@criske Te pricepi cumva la CSS/front-end development/web design? :D

**Comment by criske** [comment]
La design stau prost. :D
La capitolul web-front-end am mai avut de a face cu React, nivel incepator
cu Material Design, Hooks sau Redux.
Cel mai bine stau la mobile-dev pe android native. De fapt asta lucrez cel
mai mult :)

**Comment by amihaiemil** [comment]
@criske nah, nu trebuie React si alte prostii. Doar HTML, CSS si vanilla JavaScript sau JQuery... cel putin pentru inceput... Doar ca eu sunt absolut incompetent cand vine vorba de CSS.

**Comment by criske** [comment]
Asa pot sa scriu css dupa un graphic designer cat de cat, dar sa fac de la
mine un design nah, ma bazez pe frameworkuri css

**Comment by amihaiemil** [comment]
@criske las, ca facem cumva. Momentan incep ca toata lumea cu Bootstrap :))

**Comment by criske** [comment]
Arunca o privire si peste  https://tailwindcss.com/

**Comment by amihaiemil** [comment]
@criske plm, a innebunit lumea cu npm, webpack si mai stiu eu ce: https://tailwindcss.com/docs/installation/

All I want is a goddamn css file :))

**Comment by criske** [comment]
:)) welcome to js world
