### ISSUE TITLE
Add "Plans" Section on Homepage

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#146]
On the homepage, we should add one more Section with the "Plans". There should be 2 cards (text for now is irrelevant, it can be lorem ipsum).

Example of pricing/plan cards here: https://getbootstrap.com/docs/4.0/examples/pricing/

**Comment by amihaiemil** [comment]
@Lumi3011 can you please take care of this when you have some time? :D 

Just a section with 2 cards is enough for now -- on mobile, they should come one after another, but I think this is already the default behaviour of those bootstrap classes.

**Comment by Lumi3011** [comment]
@amihaiemil Sure, I'll try to take care of that today :D

**Comment by Lumi3011** [comment]
![image](https://user-images.githubusercontent.com/32979820/96698153-7772d000-1395-11eb-9d14-53c1760f5bdd.png)

**Comment by Lumi3011** [comment]
@amihaiemil It looks ok like this?

**Comment by amihaiemil** [comment]
@Lumi3011 yes, perfect. Please make a PR. :)

**Comment by Lumi3011** [comment]
@amihaiemil Done :D

**Comment by amihaiemil** [comment]
paid with transaction id 4A110282V3893671E

**Comment by amihaiemil** [comment]
@Lumi3011 thanks!
