### ISSUE TITLE
Write Unit Tests for Output Class JsonProject

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#152]
Similarly to how unit tests are written for JsonTask.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-09T10:10:40.239506``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@Lumi3011 Can you take care of this when you have some time? :D

**Comment by Lumi3011** [comment]
@amihaiemil Sure, I'll take care of it :D

**Comment by amihaiemil** [comment]
paid with transaction id 1X978032VP0853810

**Comment by charlesmike** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
