### ISSUE TITLE
Add "Are you sure?" Modal Question On Remove Contract

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#156]
When the user presses "Mark Contract For Removal" in the Project Contracts tab, we should ask them if they are sure they want to do that. 

<img width="754" alt="Screenshot 2020-11-02 at 16 34 02" src="https://user-images.githubusercontent.com/6305156/97880006-4d23f980-1d29-11eb-937a-de6dae87dfba.png">

I think this can be done with a Promise or something.

A more generic solution would be nice, because we need the same functionality on the Contributor Contracts tab (a Contributor can also mark their Contract for removal).

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-12T16:31:12.567126``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske Can you take care of this when you have some time? :D

**Comment by criske** [comment]
@amihaiemil  sure

**Comment by amihaiemil** [comment]
paid with transaction id 2B11268322131505U

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
