### ISSUE TITLE
Tooltip flickers when hover the "mark for removal" icon.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#158]
On my end, tooltip flickers when hover the "mark for removal" icon in Project - Contracts table.
Also the tooltip is displaced.
![mark_for_delete_tooltip_flicker](https://user-images.githubusercontent.com/10284893/97964837-13530180-1dc2-11eb-84b7-ea88e84c1815.png)

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-13T10:55:26.694839``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@criske to be honest, I have no idea what could be wrong. Is the tooltip displaced on mobile, is it maybe a responsiveness bnug?

**Comment by criske** [comment]
@amihaiemil is displaced on desktop.

**Comment by criske** [comment]
@amihaiemil maybe due to the table, it doesn't have enough room? Can you try with only one record?

**Comment by amihaiemil** [comment]
@criske that's strange. I'll try to reproduce it too. 

@Lumi3011 Can you also have a short look when you have some time?

**Comment by Lumi3011** [comment]
@amihaiemil sure, I will take a look :D

**Comment by amihaiemil** [comment]
paid with transaction id 3JU570827C353880V

**Comment by charlesmike** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
