### ISSUE TITLE
Add "Update Cash Limit" Form

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#161]
On the Project page, Wallets tab, "Real Wallet" card there should be a form with one numeric field, that will allow the PO to update the cash limit that we're allowed to use.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-13T18:56:12.059589``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2020-11-13T18:56:12). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 1DW18277MT712660P

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
