### ISSUE TITLE
getProject.js:246-247: Once the Wallet.updateCash(...)...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#170]
The puzzle `169-cede6e8a` from #169 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/cc18b6781e72a3d1699af67ab76c7217374a079c/src/main/resources/public/js/getProject.js#L246-L247

The puzzle was created by @amihaiemil on 09-Nov-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by charlesmike** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-19T11:37:39.522716``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by criske** [comment]
waiting for #139

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2020-11-19T11:37:39). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 1W14109786259881R

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
