### ISSUE TITLE
JsonInvoicedTaskTestCase.java: Continue writing unit tests f... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-web#178]
The puzzle ``173-2a3d8346`` originating from #173 has to be resolved:

https://github.com/self-xdsd/self-web/blob/d04274791aa658a4bbfc29711bab1dce04c44aa5/src/test/java/com/selfxdsd/selfweb/api/output/JsonInvoicedTaskTestCase.java#L37-L38

"Continue writing unit tests for the JSON output classes. We can continue with class JsonPayoutMethod.".

It was created by Lumi3011 on 2020-11-16T17:36:17Z. Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-27T09:50:33.110487``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-27T10:00:30.672321``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2020-11-27T10:00:30). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 2V150346D6313612F

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
