### ISSUE TITLE
ContractsApi.java: Once self-core 'Restore Contr... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-web#179]
The puzzle ``175-9e03e79b`` originating from #175 has to be resolved:

https://github.com/self-xdsd/self-web/blob/d04274791aa658a4bbfc29711bab1dce04c44aa5/src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java#L56-L59

"Once self-core 'Restore Contract' functionality for a Project Contract is available, remove the placeholder `restoreContractApi` and use the real api call. Also test constructor needs to be removed and "restore contract" unit tests updated.".

It was created by cristianpela on 2020-11-14T08:42:12Z. Estimation is ``15 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-27T09:50:40.344952``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-11-27T09:50:40). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-11-27T09:50:40). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-07T10:32:03.472117``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@Lumi3011 I removed this task from scope because the required functionality is not yet implemented in the core.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
