### ISSUE TITLE
BaseApiController.java: Implement a validation except... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-web#183]
The puzzle ``175-f102c8dd`` originating from #175 has to be resolved:

https://github.com/self-xdsd/self-web/blob/d04274791aa658a4bbfc29711bab1dce04c44aa5/src/main/java/com/selfxdsd/selfweb/api/BaseApiController.java#L40-L43

"Implement a validation exceptions handler for `ConstraintViolationException`. This is needed for `@Validated` Controllers, otherwise it will be caught by `handleInternalSeverExceptions` handler and returned as "Something went wrong while executing this request."".

It was created by cristianpela on 2020-11-13T08:48:18Z. Estimation is ``15 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-27T09:51:08.332270``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@Lumi3011 I've decided to let the PM do his job so he assigns tasks randomly to different contributors. Have a short look and if you think you can fix it, go ahead. If not, just say ``@charlesmike resign`` and the PM will look for another assignee :D

**Comment by charlesmike** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2020-11-27T09:51:08). You are past the first half of the allowed period.

**Comment by Lumi3011** [comment]
@charlesmike resign

**Comment by charlesmike** [comment]
> @charlesmike resign


@Lumi3011 ok, I'll find someone else to take care of it.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-04T19:41:52.418786``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-04T19:41:52). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-04T19:41:52). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-14T21:26:04.308222``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2020-12-14T21:26:04). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 2SW426045H305893E

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
