### ISSUE TITLE
Let's Switch to Euros

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#189]
Apparently Self's platform account on Stripe works only with Euros for some reasons.
This is a big problem: if we charge the Wallet in USD, there will be a currency conversion to Euros and we will lose money (we will not have enough money to transfer to the Contributor).

Let's just switch to Euros. Changes need to be done only on the front-end (replace any USD reference or label to EUR).

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-30T11:44:12.623218``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske FYI :D

**Comment by criske** [comment]
@amihaiemil Also
https://github.com/self-xdsd/self-web/blob/09b14d85cd23b0bb2e547d4e749932d69aeddede/src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java#L32
"$" format needs to be removed for `horlyRate` and `value` and keep the plain values.

**Comment by amihaiemil** [comment]
@criske right, good catch

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
