### ISSUE TITLE
Color for the Limit Cash in Real Wallet

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#192]
The real cash Limit should colored in:

* red if it's 0 or less than the Debt;
* yellow if limit - debt <= 100;
* green otherwise.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-04T11:09:54.099266``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
paid with transaction id 57E73293RB629215T

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
