### ISSUE TITLE
JsonPayoutMethodTestCase.java: Continue writing unit tests f... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-web#196]
The puzzle ``178-bc6ac0ac`` originating from #178 has to be resolved:

https://github.com/self-xdsd/self-web/blob/10c94ff3c1a3f0179998cb1e8bef5406f64a3b32/src/test/java/com/selfxdsd/selfweb/api/output/JsonPayoutMethodTestCase.java#L36-L37

"Continue writing unit tests for the JSON output classes. We can continue with class JsonPaymentMethod.".

It was created by Lumi3011 on 2020-11-25T18:32:23Z. Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-06T10:01:52.652646``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@charlesmike resign

**Comment by charlesmike** [comment]
> @charlesmike resign

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-06T10:32:07.843085``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2020-12-06T10:32:07). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@Lumi3011 Looks like you've missed the task deadline (2020-12-06T10:32:07). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-16T15:26:18.888406``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2020-12-16T15:26:18). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
