### ISSUE TITLE
Design the footer

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#20]
Design the footer. It should contain things such as company address, terms and cod, privacy policy etc.

**Comment by ANadrowski** [comment]
@amihaiemil I'd like to work on this issue this weekend, can you assign it to me?

**Comment by amihaiemil** [comment]
@ANadrowski Sure, thanks! 
You can see as example the footer of Travis CI: https://travis-ci.org/
I'd like something similar, with links arranged on columns.

Also, we're using Bootstrap CSS for the UI already so you probably won't have to write CSS. I think you can just use CSS classes from Bootstrap.

**Comment by ANadrowski** [comment]
@amihaiemil ok :) thanks

**Comment by ANadrowski** [comment]
@amihaiemil I just sent a PR #21. Please take a look. As always, feel free to refuse it.
Thanks.

**Comment by amihaiemil** [comment]
paid with transaction id: 27B44610C6413305H

**Comment by ANadrowski** [comment]
@amihaiemil thank you :)
