### ISSUE TITLE
Load Contracts Only on Tab Click

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#203]
On the Project page, we should load the Contracts only when the user clicks on the 'Contracts' tab.

At the moment, contracts area loaded together with the Project Overview tab and this is not always correct.

For example, the authenticated user may be an admin in the Organization which owns the repo, but we allow them to see only the Project Overview (they will not be able to load the contracts).

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-10T13:01:05.603976``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by criske** [comment]
> For example, the authenticated user may be an admin in the Organization which owns the repo, but we allow them to see only the Project Overview (they will not be able to load the contracts).

@amihaiemil I think the problem is that we don't check in `ContractsApi` if the `owner` is the same as `user` -- this leaves the door open to load contracts from any `owner` not just the org. 
The other `Contracts` endpoints have the same bug, so a separate ticket is necessary. (maybe a `Filter` could be used on the long run?)

**Comment by amihaiemil** [comment]
@criske In Contracts API we access everything via ``this.user``, so we know for sure the projects/contracts belong to them. 

Maybe I don't understand what you say :D

**Comment by criske** [comment]
@amihaiemil  You're right, somehow I've missed that :D

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
