### ISSUE TITLE
Add Pattern Validation For String Inputs

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#212]
For all the String input parameters, we should add ``@Pattern(...)`` validation and only allow alphanumeric characters + ``-`` and ``_``. Maximum length 256.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-11T21:10:50.311121``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
