### ISSUE TITLE
Show "Loading" Circle When Loading Contracts

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#215]
On the project page, Contracts tab, we should show the Loading circle. At the moment, it's not used there and the page looks like this (until the projects are displayed):

<img width="1107" alt="Screenshot 2020-12-02 at 11 19 56" src="https://user-images.githubusercontent.com/6305156/100853471-781c7d00-3490-11eb-96eb-675709eb3f4a.png">

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-12T11:21:32.717925``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
paid with transaction id 6AB20714BU795650D

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
