### ISSUE TITLE
Manual Testing Of Self-Web

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#218]
We should run some some manual tests on the front-end to make sure everything works fine.

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-12T19:59:18.716194``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-12T20:10:50.647149``.

Estimation here is ``240 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@MihaiDejeu Don't forget to close this ticket before the deadline (2020-12-12T20:10:50). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
total 8h worked and paid

**Comment by charlesmike** [comment]
@MihaiDejeu thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by amihaiemil** [comment]
@MihaiDejeu Am rezolvat urmatoarele probleme in self-web pt care nu mai trebuie sa deschizi tichete:

* sumele in Euro sunt formatate consistent peste tot (e.g.  7.5 -> 7,50; 99500.35 -> 99.500,35), inclusiv in Invoice PDF);
* problema cu avatarul intins (in Chrome si altele);
* cand se apasa pe icoana "Pay Invoice", se arata un popup cu "Are you sure?...". Acolo ii zice si ce fel de wallet foloseste;
* cand se apasa pe icoana "Edit Contract", pagina sare la form-ul respectiv (folositor pe mobile);
* alte mici fixuri legate de tab-uri: daca esti deja pe un anume tab (de exemplu Wallets) si apesi pe el, nu se intampla nimic;
* Am scos link-ul de 'Home' din header;
* in tabelul cu Task-uri, se pune spatiu (e.g. ``30 min`` in loc de ``30min``);
