### ISSUE TITLE
Choice of web framework

### ISSUE THREAD

**Issue by Guseyn** [self-xdsd/self-web#22]
Spring boot? what's wrong with Takes?

**Comment by amihaiemil** [comment]
@Guseyn I have no idea how to use takes and I don't have the time to learn it. Plus, from what I saw, I think its design is too granular.  I'm also not sure how mature Takes actually is.

As long as we have self-core designed properly, I don't mind wrapping it in a few Spring Boot annotations :)

**Comment by Guseyn** [comment]
@amihaiemil it’s sensible
