### ISSUE TITLE
On mobile, main menu avatar is stretched 

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#222]
![Screenshot_20201205-120908.jpg](https://user-images.githubusercontent.com/10284893/101239800-4c4d0180-36f3-11eb-9325-032dab73f343.jpg)

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-15T12:15:51.055191``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
