### ISSUE TITLE
Manual QA for Mobile

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#227]
Let's test it on mobile as well. Watch out especially for responsiveness bugs.

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-17T17:49:21.413056``.

Estimation here is ``240 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
finished and paid for 3h work + 30min call

**Comment by charlesmike** [comment]
@MihaiDejeu thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
