### ISSUE TITLE
Cannot download invoices using a mobile device

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#234]
Device: Samsung Galaxy S8
OS: Android 9

1. Log into application using a mobile device
2. Go to invoice list of a contract
3. Tap on the download invoice button 
**Expected outcome**: Invoice should be downloaded in the device storage
**Actual outcome**: Nothing happens
![image](https://user-images.githubusercontent.com/75386651/102010240-88acdd00-3d45-11eb-8faf-83bda54294d3.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-23T13:19:04.228``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-23T13:19:04). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-23T13:19:04). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-02T13:24:06.761605``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@criske don't bother with this. We will change this to generate the PDF server-side, anyway. :D

**Comment by criske** [comment]
@amihaiemil @MihaiDejeu I've tested on two devices and a emulator targeting Android 8, 9 and 10 and it works just fine.
For the sake of it, I might test it on real Samsung S9 device  using Samsung's [Remote Test Lab](https://developer.samsung.com/remote-test-lab), but I have a feeling that this is issue is most likely related to permissions.
@MihaiDejeu Is `Storage` permission is enabled for the browser app used to test the `self-xdsd` website? See [here](https://www.samsung.com/in/support/mobile-devices/how-to-set-individual-permissions-for-apps-in-s9-s9-plus/)

**Comment by amihaiemil** [comment]
@MihaiDejeu @criske The invoices are now generated on the server-side, so download should work fine on any device or browser. Closing this.

**Comment by amihaiemil** [comment]
paid with transaction id 0DB13079KA084634U

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
