### ISSUE TITLE
Cannot log in with a different user if the credential were already saved in the browser

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#235]
Recommend to have an extra step authentication where you can select the saved users from a list that contains all the previously saved users.
![image](https://user-images.githubusercontent.com/75386651/102010411-8c8d2f00-3d46-11eb-992d-e9187e06f82a.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-23T13:24:44.259706``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@MihaiDejeu It's not possible to do that. Authentication is done with OAuth2 protocol and Single Sign On. 
The authenticated person in Self is the same as the authenticated person in Github for that respective browser.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
