### ISSUE TITLE
Implement "User profile" page

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#236]
Should be possible to view the user profile details. This page should be accessed by using the button from main drop-down
![image](https://user-images.githubusercontent.com/75386651/102100603-4ca37600-3e32-11eb-8d90-859c31111bfb.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T17:33:39.726186``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-24T17:33:39). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-24T17:33:39). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-03T17:36:06.407934``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by criske** [comment]
@amihaiemil what aproach should be better: creating user profile page with github api data or just simply opening the user profile on github?

**Comment by amihaiemil** [comment]
@criske for now, just a page with data we have about the user in the DB (username, provider and email, at the moment).

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2021-01-03T17:36:06). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 6Y681009KG5860920

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
