### ISSUE TITLE
Change the design for the device action button from "<-" to "X"

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#238]
When using the mobile device, the action button from closing the application indicates a back button. This is really confusing. If the purpose is for closing the application then the design should be "X"

![image](https://user-images.githubusercontent.com/75386651/102101453-54174f00-3e33-11eb-9d2d-0f3395de49f4.png)

**Comment by charlesmike** [comment]
@MihaiDejeu thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T17:43:36.486052``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@MihaiDejeu That's the "Back" button of your mobile browser. We cannot change that, it depends on the browser.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
