### ISSUE TITLE
Should not be possible to add, as a payment method, the same credit card multiple times

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#239]
1. Navigate to the "Wallet" page for a certain repository
2. Go to the "Real Wallet" section,
3. Add a card as a payment method
4. Add the same credit card one more time
Expected result: A validation should occur and user is not allowed to add the same card twice
Expected result: User is allowed to add the same card as many time he/she wants
![image](https://user-images.githubusercontent.com/75386651/102102506-8ffee400-3e34-11eb-9435-332e2b53ef3b.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T17:48:52.192785``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@MihaiDejeu This is 100% Stripe behaviour. Maybe they allow you to add the same card because we are in Test. 

In any case, we cannot interfere with this because we do not have access to the card data.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
