### ISSUE TITLE
Table footnote doesn’t update correctly based on entries per page

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#242]
1. Go to the Contracts of a specific repository
2. Change to show 25 entries
**Expected result**: In my case, should have been “Showing 1 to 2 of 2 entries”
**Actual result**: It display "Showing 1 to 25 of 25 entries"
![image](https://user-images.githubusercontent.com/75386651/102106129-e0784080-3e38-11eb-9c18-54bea788197d.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T18:19:33.804982``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-24T18:19:33). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-24T18:19:33). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-03T18:24:06.813201``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2021-01-03T18:24:06). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
