### ISSUE TITLE
Newly created invoices are not displayed when pressing the “See Tasks” button

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#244]
1. GO to a contract
2. Pay an invoice -> Invoice is "Paid"
3. Press on the reload button for the paid invoice at step 2
**Expected result**: The new invoice should be displayed
**Actual result**:  The new invoice is not displayed until the contract list is refreshed
![image](https://user-images.githubusercontent.com/75386651/102107069-fc301680-3e39-11eb-9272-916c37ecbf87.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T18:26:22.199926``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@charlesmike quit

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-26T14:46:38.253028``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by criske** [comment]
@amihaiemil The new invoice has 0 amount. Should we allow to pay it, if is empty?

**Comment by amihaiemil** [comment]
@criske nope, I forgot to do that flow :D

**Comment by amihaiemil** [comment]
paid with transaction id 8XE92008GE0421831

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
