### ISSUE TITLE
Add a more suggestive validation text when trying to create a new contract for the same user with the same role

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#246]
1. Create a contract for **MihaiDejeu** with role **DEV**
2. Create a new contract for the same user, **MihaiDejeu** with role **DEV**
![image](https://user-images.githubusercontent.com/75386651/102107896-ec650200-3e3a-11eb-8bf0-075cfedde839.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T18:34:36.322975``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-24T18:34:36). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-24T18:34:36). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-03T18:39:50.329795``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2021-01-03T18:39:50). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@Lumi3011 Looks like you've missed the task deadline (2021-01-03T18:39:50). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-13T19:00:21.200017``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@fellahi-ali Don't forget to close this ticket before the deadline (2021-01-13T19:00:21). You are past the first half of the allowed period.

**Comment by fellahi-ali** [comment]
@charlesmike wait please!

**Comment by charlesmike** [comment]
> @charlesmike wait please!

@fellahi-ali didn't understand that, sorry.

**Comment by fellahi-ali** [comment]
@amihaiemil I'm still working on this, Is there a way to make _charlsemike_ wait for me?

**Comment by amihaiemil** [comment]
@fellahi-ali nope, there is no ``wait`` functionality yet. But you still have 4 days. 

Don't worry, even if it takes it away from you, I will assign it back :D

**Comment by amihaiemil** [comment]
@fellahi-ali oh, no, actually the deadline is today. Let me fix it.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by fellahi-ali** [comment]
> @fellahi-ali oh, no, actually the deadline is today. Let me fix it.

@amihaiemil many thanks!

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-23T19:56:12.245084``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
paid with transaction id 8BL82782JR0783548

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
