### ISSUE TITLE
Console error when refreshing the contract list for MihaiDejeu/self-QA repository

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#247]
**Browser: Chrome 87.0.4280.88**

1. GO to **MihaiDejeu/self-QA** repository
2. GO to **Contracts** tab
![image](https://user-images.githubusercontent.com/75386651/102108226-5382b680-3e3b-11eb-92ca-57a3ca99cdee.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T18:37:30.315090``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@MihaiDejeu This is expected because pagination on the backend is not yet implemented si that URL does not exist (404). There is a fallback mechanism in this case, to fetch all contracts.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
