### ISSUE TITLE
When clicking outside of the "Update cash limit" pop-up this should be closed

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#249]
1. Go to the **Wallets** tab of a certain repository
2. Open the "Update cash limit" pop-up
3. Click outside the pop-up 
Expected result: Pop-up should be closed
Actual result: Pop-up remain opened and when you navigate to a different tab, this will still be displayed
![image](https://user-images.githubusercontent.com/75386651/102115095-bb3cff80-3e43-11eb-9e1a-f4d142364c61.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T19:37:09.205378``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@charlesmike quit

**Comment by charlesmike** [comment]
> @charlesmike quit

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-26T14:37:37.711125``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
