### ISSUE TITLE
When pressing the My Repositories or Contributor Dashboard buttons, for a fraction of second, home screen buttons are displayed

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#250]
![image](https://user-images.githubusercontent.com/75386651/102115238-f50e0600-3e43-11eb-9f56-f8126907fb2d.png)
![image](https://user-images.githubusercontent.com/75386651/102115275-00613180-3e44-11eb-9869-d99da000ace8.png)
![image](https://user-images.githubusercontent.com/75386651/102115305-0c4cf380-3e44-11eb-90c9-cf6d7a60dc33.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T19:39:29.735082``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
