### ISSUE TITLE
When navigating back from the "Stripe Dashboard" page, user should be redirected to the "Payout Methods" page

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#253]
1. Go to the **Contributor Dashboard**
2. Go to **Payout Methods** page
3. Go to **Stripe Dashboard** page
4. Go back
Expected result: User should be taken back to step 2 **Payout Methods** page
![image](https://user-images.githubusercontent.com/75386651/102116621-e4f72600-3e45-11eb-8810-c155e8c5fb25.png)

Actual result: User is taken the the **Repository overview** page
![image](https://user-images.githubusercontent.com/75386651/102116580-d872cd80-3e45-11eb-9ca1-394b19e3df9b.png)

**Suggestion**:  **Stripe Dashboard** page should be opened in a new tab

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T19:54:10.808596``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@charlesmike resign

**Comment by charlesmike** [comment]
> @charlesmike resign

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-26T14:34:36.992879``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2020-12-26T14:34:36). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
