### ISSUE TITLE
Cannot pay invoices 82 and 108 from MihaiDejeu/self-QA repository

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#255]
**Fake Wallet** is used for the **MihaiDejeu/self-QA** repository

Please investigate why this error occurs when trying to pay the following invoices
![image](https://user-images.githubusercontent.com/75386651/102117634-3ce25c80-3e47-11eb-9882-f6d5b18af762.png)

![image](https://user-images.githubusercontent.com/75386651/102117791-7024eb80-3e47-11eb-81e3-f28839b6ae5f.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T20:04:17.933328``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-24T20:04:17). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-24T20:04:17). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-03T20:09:06.595552``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu Don't forget to close this ticket before the deadline (2021-01-03T20:09:06). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@MihaiDejeu Looks like you've missed the task deadline (2021-01-03T20:09:06). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-14T01:00:16.705791``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@Lumi3011 I fixed a few bugs regarding invoice payments already, so this is most likely fixed.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
