### ISSUE TITLE
The job fails when adding a label that refer to a very large number of minutes

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#256]
![image](https://user-images.githubusercontent.com/75386651/102118603-9b5c0a80-3e48-11eb-9512-2a606e1c115c.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T20:12:51.876827``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
Fixed. If the number has more than 6 digits it is ignored and the default estimation of 60min/30min is applied.

Initially we wanted to add the maximum estimation (360min) in this case, but if someone adds a label with 7 digits in minutes, they are clearly not being serious :)

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
