### ISSUE TITLE
"Home" page UI improvements

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#257]
**Improvement 1:**
Remove “project” from the description
1. 
![image](https://user-images.githubusercontent.com/75386651/102119494-dc085380-3e49-11eb-8c89-16809a6f680c.png)
2. 
![image](https://user-images.githubusercontent.com/75386651/102119504-e1659e00-3e49-11eb-94bd-0aea263ec017.png)

**Improvement 2:**
Align the text vertically (set to the middle of the element looking to the picture next to it)
1. 
![image](https://user-images.githubusercontent.com/75386651/102119559-f6dac800-3e49-11eb-8a53-34992ec17da5.png)
2. 
![image](https://user-images.githubusercontent.com/75386651/102119591-05c17a80-3e4a-11eb-857b-9a78b5aaad92.png)

**Improvement 3:**
Stretch the header buttons disposal (menu buttons should start more from the left and the profile picture move more on the right). Check how it’s made for www.github.com for example.
![image](https://user-images.githubusercontent.com/75386651/102119739-43be9e80-3e4a-11eb-86f9-087752e879b1.png)

**Improvement 4:**
Make this 2 cards even
![image](https://user-images.githubusercontent.com/75386651/102119871-723c7980-3e4a-11eb-9f28-5430acbc03b6.png)

**Improvement 5:**
Remove the “Home” button as it's clear enough that by clicking on the logo, user will be taken to "Home"
![image](https://user-images.githubusercontent.com/75386651/102120109-bb8cc900-3e4a-11eb-925f-077c595cde13.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T20:24:00.423384``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-24T20:24). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-24T20:24). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-03T20:27:47.679549``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu Don't forget to close this ticket before the deadline (2021-01-03T20:27:47). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@MihaiDejeu Looks like you've missed the task deadline (2021-01-03T20:27:47). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-14T01:00:24.312901``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@fellahi-ali most of this is already done. I'll deregister it

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
