### ISSUE TITLE
Improvements for table pagination, search input and filters

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#258]
**Improvement 1:**
Move "Show entries per page" before the pagination
![image](https://user-images.githubusercontent.com/75386651/102120518-52f21c00-3e4b-11eb-886b-31be241dcc72.png)

**Improvement 2:**
Make it possible to search only by the elements of the first column ID/Issue/Contributor

**Improvement 3:**
Add a placeholder to search by the corresponding table element.
Example: "_Search by contributor_"
![image](https://user-images.githubusercontent.com/75386651/102120573-67ceaf80-3e4b-11eb-9716-6f2c1517fce6.png)

**Improvement 4:**
Make it possible to search by **Assigned** and **Deadline** as time interval (to search by a value within a certain timespan). One filter for each column

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-24T20:36:16.605121``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-24T20:36:16). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-24T20:36:16). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-03T20:39:46.644552``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2021-01-03T20:39:46). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@criske Looks like you've missed the task deadline (2021-01-03T20:39:46). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-14T01:00:32.065781``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@fellahi-ali there is already a PR provider by @criske, I'll deregister this :D

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
paid with transaction id 2CN33101047252424
