### ISSUE TITLE
"Tasks" card improvements

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#262]
**Improvement 1:**
Add also the **Closed** tasks. It would be helpful for having an overview and tracking inside Self

**Improvement 2:**
Add a new column **Status**.  Tasks will have 2 statuses - **Active** or **Closed**
Add a filter by status - Multiselect with 2 options (Active and Closed)
Do not set ordering ascending/descending on this column

**Improvement 3:**
Add a new column **Invoice Number** - It would be helpful for having an overview and tracking inside Self
For closed tasks, add the **Invoice Number**. For active ones display “-” or "N/A"

**Improvement 4:**
Change from “Issue” to “Issue ID”

**Improvement 5:**
Add space before min
![image](https://user-images.githubusercontent.com/75386651/102231933-34495f00-3ef7-11eb-89ef-d43c90603126.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-25T17:02:05.113072``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-25T17:02:05). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-25T17:02:05). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-04T17:03:48.409773``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu Don't forget to close this ticket before the deadline (2021-01-04T17:03:48). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@MihaiDejeu Looks like you've missed the task deadline (2021-01-04T17:03:48). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-14T18:59:50.615874``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2021-01-14T18:59:50). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 93J362600H860702X

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
