### ISSUE TITLE
"Invoices" card and template improvements

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#264]
**Improvement 1:**
For Invoices table change column from **ID** to **Invoice ID**

**Improvement 2:**
Remove ordering from the "Status" and "Options" columns of the **Invoices** table 

**Improvement 3:**
Remove title
![image](https://user-images.githubusercontent.com/75386651/102233725-3dd3c680-3ef9-11eb-9a3d-4875de90db1e.png)

**Improvement 4:**
Put the “Invoice #108 from 2020-12-13" at the same level where “Invoice” was but indented to the left
![image](https://user-images.githubusercontent.com/75386651/102233945-74a9dc80-3ef9-11eb-8f76-d6c72b0c6eee.png)

**Improvement 5:**
Change from “github” to “GitHub”
![image](https://user-images.githubusercontent.com/75386651/102234060-91deab00-3ef9-11eb-99d7-7c5d0e0bf4d4.png)

**Improvement 6:**
Change from “DEV” to “Developer” (make this change after **#263 - Improvement 3**)
![image](https://user-images.githubusercontent.com/75386651/102234112-a15df400-3ef9-11eb-9bdb-d32e875178db.png)

**Improvement 7:**
Add a dash before the sub elements: to Contributor, to Project Manager, paid at, payment due
![image](https://user-images.githubusercontent.com/75386651/102234349-dd915480-3ef9-11eb-8b21-58c684120310.png)

**Improvement 8:**
Change from "active" to "Active"
![image](https://user-images.githubusercontent.com/75386651/102234704-3a8d0a80-3efa-11eb-9350-b5608e56f84d.png)

**Improvement 9:**
Change from “paid” to “Paid”
![image](https://user-images.githubusercontent.com/75386651/102234803-54c6e880-3efa-11eb-8d07-2c18ab1d097e.png)

**Improvement 10:**
Remove **transaction id** for paid invoices
![image](https://user-images.githubusercontent.com/75386651/102234920-71fbb700-3efa-11eb-9478-4edc9d39b859.png)

**Improvement 11:**
Place “Invoiced tasks below” beneath the section line, right above the task table and remove “bellow”
![image](https://user-images.githubusercontent.com/75386651/102235130-b12a0800-3efa-11eb-9bc2-0b88a7466d67.png)

**Improvement 12:**
Stretch the **Tasks** table along the whole page
![image](https://user-images.githubusercontent.com/75386651/102235242-cc951300-3efa-11eb-8367-43ca5610490d.png)

**Improvement 13:**
Change from “Commission” to “PM Commission”
![image](https://user-images.githubusercontent.com/75386651/102235295-dc145c00-3efa-11eb-9807-934ed2645e5e.png)

**Improvement 14:**
Have all the values from the table aligned to the left.
![image](https://user-images.githubusercontent.com/75386651/102235397-f64e3a00-3efa-11eb-9ef4-ae2520a579be.png)

**Improvement 15:**
For payment due, show the date. You can specify between the brackets (next Monday)
![image](https://user-images.githubusercontent.com/75386651/102235598-27c70580-3efb-11eb-9f01-2fa5f69086e2.png)

**Improvement 16:**
Remove the . (dot) after “Monday”
![image](https://user-images.githubusercontent.com/75386651/102235646-357c8b00-3efb-11eb-89f9-887caaf09b84.png)

**Improvement 17:**
Add space before the next page, in case the tasks table stretch between multiple pages
![image](https://user-images.githubusercontent.com/75386651/102235822-6957b080-3efb-11eb-830b-117854c0342e.png)

**Improvement 18:**
Add “Assigned Date” and “Closed Date” in the table for a better tracking and overview.

**Improvement 19:**
I still don’t see the importance of having the **due to PM** in the invoice that **contributor** sees

**Improvement 20:**
Order the invoices descending by default so the active invoice always be first. This way you don't have to navigate to the last page to reach to the Active invoice.
![image](https://user-images.githubusercontent.com/75386651/102239511-9ad27b00-3eff-11eb-8cae-8055cdfc4c1f.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-25T17:19:18.082990``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-25T17:19:18). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-25T17:19:18). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-04T17:24:06.494936``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
Not applicable anymore. The Invoice PDF is now generated server-side with a completely different template.

**Comment by charlesmike** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
