### ISSUE TITLE
"Update cash limit" pop-up improvements

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#265]
**Improvement 1:**
When updating the limit update, confirmation button should be a **check sign** not reload
![image](https://user-images.githubusercontent.com/75386651/102237301-37474e00-3efd-11eb-87ee-c35d85a53f01.png)

**Improvement 2:**
After accepting the new limit, pop-up should close
![image](https://user-images.githubusercontent.com/75386651/102237392-4af2b480-3efd-11eb-96e1-2e3c64197192.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-25T17:46:27.413``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@charlesmike refuse

**Comment by charlesmike** [comment]
> @charlesmike refuse

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by amihaiemil** [comment]
@criske the icon is fine, I think. Just the popup disappear when the update is finished :D

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-26T14:58:37.714153``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
