### ISSUE TITLE
Improvements when working with tables using a mobile device

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#267]
**Improvement 1:**
When sliding through the tables, pagination elements should remain still
![image](https://user-images.githubusercontent.com/75386651/102238589-978abf80-3efe-11eb-9daf-4568215ac273.png)

**Improvement 2:**
Add space between **Tasks** and **Invoices** tables
![image](https://user-images.githubusercontent.com/75386651/102238834-e20c3c00-3efe-11eb-8fe2-448f46eb159b.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-25T17:55:11.742995``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-25T17:55:11). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2020-12-25T17:55:11). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-04T18:00:06.927947``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2021-01-04T18:00:06). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@Lumi3011 Looks like you've missed the task deadline (2021-01-04T18:00:06). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-14T19:00:15.975702``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by amihaiemil** [comment]
@Lumi3011 Aici, cu prima parte, nu-ti bate capu, nu fa nimic. Avem deja un PR cu destul de multe schimbari al tabele (#311), si cel mai probabil sunt acoperite deja.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-16T09:48:54.892792``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2021-01-16T09:48:54). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 9JD60868VL1539932

**Comment by charlesmike** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
