### ISSUE TITLE
After setting up Stripe wallet, real wallet is not shown.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#282]
After setting up Stripe wallet, real wallet contents are not shown, only after comming back on `Wallets` tab.

Initial, before clicking `Setup Stripe Wallet`:
![screencapture-localhost-8080-github-criske-app-portfolio-2020-12-19-12_18_01](https://user-images.githubusercontent.com/10284893/102689191-da9da900-4204-11eb-9e8c-3d8bca765fd9.png)

After clicking:
-  Expected
![screencapture-localhost-8080-github-criske-app-portfolio-2020-12-19-12_27_05](https://user-images.githubusercontent.com/10284893/102689204-ebe6b580-4204-11eb-9150-b728f22a5ad3.png)
- Actual
![screencapture-localhost-8080-github-criske-app-portfolio-2020-12-19-12_18_47](https://user-images.githubusercontent.com/10284893/102689226-16387300-4205-11eb-938e-f04d31ccf0b0.png)

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-29T14:25:04.423554``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2020-12-29T14:25:04). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@Lumi3011 Looks like you've missed the task deadline (2020-12-29T14:25:04). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-08T14:28:03.248085``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@fellahi-ali this is just a show/hide problem. In the ``success`` callback of the ajax call to the backend, we should simply display the right div. Have a look on what divs are there and their IDs. You can mock the ajax call, no need to actually call the backend :D

**Comment by fellahi-ali** [comment]
@amihaiemil thanks for the hint :) will take a look on it soon.

**Comment by charlesmike** [comment]
@fellahi-ali Don't forget to close this ticket before the deadline (2021-01-08T14:28:03). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 8N786435X0220394N

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
