### ISSUE TITLE
getAndAddContracts.js: On frontend, in Contracts tab... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-web#285]
The puzzle ``253-06bb9d7e`` originating from #253 has to be resolved:

https://github.com/self-xdsd/self-web/blob/fe93595e7b8642e442be5a321f925b8be2139029/src/main/resources/public/js/getAndAddContracts.js#L14-L16

"On frontend, in Contracts tab, after adding a new contract, we should add the new contract to contract table, instead of updating table by re-fetching all contracts again. Same logic should be applied to "markContractForRemove" and "restoreContract".".

It was created by cristianpela on 2020-12-19T11:15:15Z. Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-02T12:30:08.725748``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-01-02T12:30:08). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2021-01-02T12:30:08). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-12T12:59:35.684043``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2021-01-12T12:59:35). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 9HP435415N2669009

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
