### ISSUE TITLE
Onboarding Task

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#289]
self-web is a simple Spring Boot application with a few pages (HTML5, Bootstrap 4, CSS3) which are calling the backend endpoints using Jquery. The tabs on the Project page and the Contributor Dashboard are just some show/hide magic using jquery.

There is also a bit of templating going on: that part is taken care of by Thymeleaf, which comes together with Spring Boot, out of the box.

The authentication is done with Oauth2 from Spring Security and the endpoints are declared as RestControllers. Input validation is done using Java Bean Validation and the output is implemented using JsonObjects and JsonArrays.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-05T13:23:20.198997``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@fellahi-ali Don't forget to close this ticket before the deadline (2021-01-05T13:23:20). You are past the first half of the allowed period.

**Comment by fellahi-ali** [comment]
@amihaiemil I have successfully started self web app locally :) but still working on understanding how things are wired, and have some newbie questions:
- I have logged in with my real github account, I can't figure out otherway, is that how it's supposed to work in test env?
- After logging I noticed there is only 100 github repos listed and can't see others (I have a lotof forks :D that I can't get to my own projects)
- There is nothing on the contributor tab, do I need to activate some real project and add myself as contributor?
- To work on #282, do I need to setup a real wallet? Are there no issues about that, or the app is connected to some test API?

**Comment by amihaiemil** [comment]
@fellahi-ali 

* > I have logged in with my real github account,

Yes, you are always using your real Github account, there is no other way.

* > After logging I noticed there is only 100 github repos listed 

Yes, at the moment only 100 repos are listed, we should implement the pagination there. You can open a ticket for that in self-web. I didn't bother with pagination yet becuase there are very few developers who have more than 100 repos... I have about 75 after 5 years of Github.

* > There is nothing on the contributor tab

Yes, there is nothing because you are working with your local DB and you are not registered as a Contributor in any project. If you activate a Project, you will automatically have a Contract with role PO for that Project.

* > Test Stripe

You are using the Test Environment in Stripe (dictated by the Stripe Test Key I gave you). Also make sure to set up the ``testenv`` variable of Self to ``true`` (you should see the big red banner: "This is a Test version... ")

But keep in mind, in order to work on #282 it is not necessary to actually call the backend endpoint, you can mock that call. As I said, the problem is in the ``success`` callback function in the front-end :D

**Comment by amihaiemil** [comment]
paid with transaction id 7RB72643YB515735W

**Comment by fellahi-ali** [comment]
@amihaiemil Thanks for the answers :)
> becuase there are very few developers who have more than 100 repos... I have about 75 after 5 years of Github.
huh I do :D but most of them are forks, a time ago I was obsessed with collecting interesting repos in my account hoping to work/use them someday, but I think it's time to clean up.

>But keep in mind, in order to work on #282 it is not necessary to actually call the backend endpoint, you can mock that call. As I said, the problem is in the success callback function in the front-end :D
Actually I'm not very familiar with JQuery and Frontend dev in general, but I will try to figure that out and learn along the way. I hope :)

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by criske** [comment]
@fellahi-ali Here is what I do when working with local db. A good starting point is to use these scripts https://github.com/self-xdsd/self-storage/tree/master/src/test/resources . It helps to have an application to manage the db too. I'm using `MySQL Workbench`. So before starting the self web app, I'm running with worbench the above scripts (schema first and then insertions).

Also you might need to modify `insertTestData.sql` according to your needs. For example if you have a real repo and you want to be already active just add:
```sql
INSERT INTO self_xdsd.slf_projects_xdsd
(repo_fullname, provider, username, pmid, webhook_token)
VALUES ('fellahi-ali/my-real-repo', 'github', 'fellahi-ali', 1, 'whtoken123');
```
Also make sure that your username is registered first:
```sql
INSERT INTO self_xdsd.slf_users_xdsd
(username, provider, role, email)
VALUES ('fellahi-ali', 'github', 'user' ,'fellahi-ali@example.com');
```
And from now on you can also add sql instructions for contributors (not necessary real), fake tasks etc...

On front-end, sometimes you can use jquery to intercept ajax calls and mock server responses. I use `jquery.mockjax` for that.
Here is an example on how jquery is used to mimic a response similar to project contracts https://github.com/criske/editable-datatable.

**Comment by fellahi-ali** [comment]
Many thanks @criske for the great insights, that would be very helpful :)

**Comment by fellahi-ali** [comment]
@amihaiemil @criske Sorry! but I'm still confused about one thing :(
How do you handle the code related to this kind of tasks (i.e: js code for that ajax mock & call), should it be part of the PR? if so where I should put it? as I don't see anything similar in the **test/** dir (only api tests). Or I could just write some throwaway code to figure out where the problem is and only contribute the **fix**?
I'm really interested to know how do you handle these situations, as I'm really bad at thinking out of the box :(

**Comment by criske** [comment]
@fellahi-ali Mocking code/js files should not be part of the PR (you can git ignore them). But than again is better to interact directly with the `self-web` server and use mocking calls as a last resort. :D. As long as you have some data in your local db it should be fine to test most of the frontend stuff.

**Comment by amihaiemil** [comment]
@fellahi-ali this kind of code is throw-away code which you use just to get the fix in place. :D
