### ISSUE TITLE
Better Table Loading Approach

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#294]
As per [this](https://github.com/self-xdsd/self-web/pull/293#discussion_r549733804) comment, we should have a more elegant approach to loading data into tables.

```javascript
$("#table").dataTable({
     language: { loadingRecords: '<img src=...>' },
     ajax: function(_, callback){
         callRemote(...).then(remoteData => {
             callback({data: remoteData.map(toTableRow)})
         })
     }
});
```

Let's start by modifying Tasks and Invoices tables on the Project page, then make the same changes for the tables on the Contributor Dashboard page.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-08T17:18:30.164716``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
paid with transaction id 95B2185622713600F

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
