### ISSUE TITLE
The "Real Wallet" details disappear after the stripe account was created.

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#295]
Steps to reproduce:
1. As a product owner, access "My Repository"
2. Select any project.
3. Go to "Wallets" menu
4. At the "Real Wallets", select "Individual"
5. Fill in all the mandatory fields for Stripe account
6. Accept terms and conditions.
7. Press the "Setup Stripe Wallet" button.
![image](https://user-images.githubusercontent.com/76066892/103169662-7b641800-4846-11eb-8f73-b8a7519477fc.png)

Expected outcome:
Detail for "Real Wallet" are displayed. 
![image](https://user-images.githubusercontent.com/76066892/103169649-638c9400-4846-11eb-849a-d0fd477c03d3.png)

Actual outcome:
The real wallet details disappear after the stripe account was created.
![image](https://user-images.githubusercontent.com/76066892/103169673-8fa81500-4846-11eb-8846-7e226ca0be2e.png)

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-08T21:25:52.732906``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@MihaiDejeu this problem is already reported: https://github.com/self-xdsd/self-web/issues/282
