### ISSUE TITLE
getContributor.js: Better table loading approach... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-web#297]
The puzzle ``294-8576cb35`` originating from #294 has to be resolved:

https://github.com/self-xdsd/self-web/blob/6b4102256289ee6a10ef5bc23a06d4e1e3272030/src/main/resources/public/js/getContributor.js#L2-L3

"Better table loading approach for Contributor dashboard tables. Use the same approach specified at issue #294.".

It was created by @amihaiemil on 2020-12-30T12:27:47Z. Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-09T15:15:50.877282``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
paid with transaction id 17C975111G1312541

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
