### ISSUE TITLE
Allow Invoice Payment Only If totalAmount >= 108 EUR

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#300]
We made this change in the core, but we also have to do it on the web UI.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-10T14:11:00.183294``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske this is one of the more urgent issues. Can you fix it these days when you have some time? :D

**Comment by criske** [comment]
@amihaiemil  I'll fix asap  :)

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2021-01-10T14:11). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 8DE32677XW123643X

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
