### ISSUE TITLE
Contract Agenda Button Broken on Contributor Dashboard

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#302]
On the Contributor Dashboard page, the Contract Agenda button does not work for any Contract. There's an undefined variable there:

<img width="1440" alt="Screenshot 2020-12-31 at 18 42 50" src="https://user-images.githubusercontent.com/6305156/103418678-62d26580-4b98-11eb-81e5-3d5a6ae99a9c.png">

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-10T18:46:23.093049``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske it's not urgent, whenever you have time :D

**Comment by criske** [comment]
@amihaiemil sorry about that, I've forgot to extract the contract from table data, like I did at line 27. I'll fix it asap.

**Comment by amihaiemil** [comment]
@criske no problem, happens

**Comment by amihaiemil** [comment]
paid with transaction id 85Y156357F5311033

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
