### ISSUE TITLE
Options Buttons Don't Work On 2nd Page Of Table

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#306]
On the Contributor Dashboard page, the Options buttons (Contract Agenda, Mark For Removal) are not working on the second and later pages. This might also be a problem in other tables. As far as I can tell, it's related to the new table loading approach. 

<img width="1101" alt="Screenshot 2021-01-02 at 11 09 24" src="https://user-images.githubusercontent.com/6305156/103454284-25322180-4ceb-11eb-8ed7-3e8ae13bffe8.png">

The problem is most likely that the event listeners are only appended to the elements visible on the first page of the table.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-12T11:11:39.750280``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by criske** [comment]
@amihaiemil yep, I was about to open an issue about this too. I played a bit with datatables to find a way to edit cells (maybe we can use it to update contracts from table directly). Anyway the fix is to register listeners on draw callback. I'll open a pr asap.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
