### ISSUE TITLE
Contract hourlyRate BigDecimal With No Decimals

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#308]
The Contract hourly rate (for new contract or update contract) reaches the backend as ``double`` and then it is only divided by ``100``, but the resulting BigDecimal is not rounded. 

The BigDecimal should be rounded so that it has no decimals, since this value represents the lowest denomination, the cents.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-12T14:43:10.393210``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
