### ISSUE TITLE
Delete pdf invoice from server after it was downloaded.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#314]
We should delete the pdf invoice from server after it was generated and downloaded by the client.

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-15T16:48:55.574116``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike quit

**Comment by charlesmike** [comment]
> @charlesmike quit

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by amihaiemil** [comment]
@criske we should also add a unique identifier to the PDF file-name. At the moment, both the Client endpoint (used by the PO on the Contracts page) and the Contributor endpoint (used by the Contributor on the Dashboard page) are generating the file with the same name in the same location.

This is already a problem, if they are downloading the file at the same time, they can override each other's files and with delete functionality, they might delete the file when the other is trying to download it as well.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-15T16:58:49.479933``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by criske** [comment]
@amihaiemil Even without deleting, there might still be a problem when PO and Contributor are writting the pdf in the same time.
So yeah, either using your aproach with generated id/different folder or an even simpler aproach:
Write the whole thing into the `OutputStream` given by `StreamingResponseBody`. `PDDocument#save` supports `OutputStream` + it handles the closing too.
We only need to change `File::Invoice#toPdf()`  to `void::Invoice.toPdf(OutputStream)`.

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2021-01-15T16:58:49). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@criske the OutputStream seems to be the best option, then we just stream it directly to the client. Go ahead with it :D

**Comment by criske** [comment]
@amihaiemil I've opened an issue on core.

**Comment by amihaiemil** [comment]
@criske right, thanks!

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
