### ISSUE TITLE
Display "Download Self PDF" for Contributors

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#315]
On the Contributor Dashboard page, Invoices table, for each Invoice which has been paid with a real wallet, next to the Download Invoice button (which downloads the Invoice of the Contributor to the Project), we should have a second Download Invoice button, which will download the Invoice from Self to the Contributor.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-16T12:03:16.942977``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-01-16T12:03:16). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
