### ISSUE TITLE
LoginProducer.java: Write unit tests for LoginPro... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-web#321]
The puzzle ``685751060`` originating from #40 has to be resolved:

https://github.com/self-xdsd/self-web/blob/bf574b14bfdedc818f8774694500524750efe2c7/src/main/java/com/selfxdsd/selfweb/LoginProducer.java#L43-L44

"Write unit tests for LoginProducer covering login cases for Github and Gitlab providers.".

Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-17T10:49:42.115515``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by nmonokov** [comment]
@amihaiemil Hi! I'd like to work on this one. I want to improve my Java skills and your projects look very good.

**Comment by amihaiemil** [comment]
@charlesmike add

**Comment by charlesmike** [comment]
> @charlesmike add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@nmonokov this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-06T07:04:02.511134``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@nmonokov I registered a Contract for you in Self XDSD, you can see it hese: http://self-xdsd.go.ro. 
Please send me your PayPal e-mail address :)

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@nmonokov thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by amihaiemil** [comment]
paid with transaction id 9A118935EL518691A
