### ISSUE TITLE
Some HTML code explanation needed?

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-web#324]
@amihaiemil I can't understand what is these two lines supposed to do?  

https://github.com/self-xdsd/self-web/blob/2d3f846e2f3fe251608a0a50e9de2a4b16ab7a0a/src/main/resources/templates/index.html#L16-L17

https://github.com/self-xdsd/self-web/blob/2d3f846e2f3fe251608a0a50e9de2a4b16ab7a0a/src/main/resources/templates/index.html#L21-L22

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-19T22:06:12.006652``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@fellahi-ali to be honest, I am not sure. Maybe I added them for styling purposes. But why do you ask? :D

**Comment by fellahi-ali** [comment]
@amihaiemil Sorry for  not providing context to the question :(
Actually I was working on #237 and trying different CSS properties and adding/removing HTML elements (kind of newbie experimentations :)  then noticed that those two `div`s are hidden (by `d-none` prop), and don't add anything to the page just noise, but I was not sure maybe I was missing something, so I asked :) 
and if they are not used for anything for sure, maybe I should remove them to simplify the HTML code a bit.

**Comment by amihaiemil** [comment]
@fellahi-ali Yes, you can remove them if they're not doing anything. But also test the mobile version to see if the removal doesn't break anything -- maybe they do something for mobile, I'm not sure :D

**Comment by amihaiemil** [comment]
@fellahi-ali I'm closing this :D

**Comment by charlesmike** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
