### ISSUE TITLE
Links to issues in the Tasks card on the Dashboard are broken 

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-web#327]
All issues links point to _http://self-xdsd.go.ro/contributor#_
![issue-links-brocken](https://user-images.githubusercontent.com/25110612/104139959-0d276580-53af-11eb-9600-faa4d03cf365.png)

- Actual behaviour:
Links point to _http://self-xdsd.go.ro/contributor#_
- Expected behaviour:
Eash link should open the corresponding issue on Github.

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-21T03:06:39.262507``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by amihaiemil** [comment]
@criske can you pls have a look? :D

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-21T09:36:13.416694``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
