### ISSUE TITLE
Adapt UI for GitLab

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#335]
The backend GitLab integration is finished, so we can start with the front-end.

The problem is that there are a some places in the front-end where github is hardcoded. Instead, the logic should be chosen based on the user's provider.

I think a good place to start is the ``Add New Contract`` formular, which has a few things hardcoded for Github.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-23T12:27:17.514613``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2021-01-23T12:27:17). You are past the first half of the allowed period.

**Comment by criske** [comment]
wait for self-core [0.0.55](https://github.com/self-xdsd/self-core/issues/918l)

**Comment by criske** [comment]
@amihaiemil We got a problem. Gitlab require authenticated requests for their [ Search API](https://docs.gitlab.com/ee/api/search.html) . I think we got no choice but to create an endpoint for [find users](https://docs.gitlab.com/ee/api/search.html#scope-users).
Checking if user exists works without auth though.

**Comment by amihaiemil** [comment]
@criske let's just ignore it for now -- in the case of GitLab, there will be no autocompletion at the moment :D

**Comment by amihaiemil** [comment]
@criske FYI ``self-core 0.0.55`` is released. You also need to update the ``storage to 0.0.25``, otherwise it won't work :D

**Comment by amihaiemil** [comment]
paid with transaction id 95F99785106479447

**Comment by criske** [comment]
> paid with transaction id 95F99785106479447

Mersi mult Mihai :D , dar e prea mult, mi-a luat cam vreo 4 ore cu tot cu teste, totul in decurs de cateva zile. Urmatoarele 5-6 bounty uri o sa le consider ca facand parte din asta (o sa merg pe no bounty) :D

**Comment by amihaiemil** [comment]
@criske ok :D

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
