### ISSUE TITLE
head.html: . We should have a global js ... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-web#343]
The puzzle ``-1750085019`` originating from #335 has to be resolved:

https://github.com/self-xdsd/self-web/blob/f1ec7859ab4d91a648eabc08cd26929f9935f272/src/main/resources/templates/head.html#L30-L35

". We should have a global js variable `provider` that will be initialized when `/api/users/self` call in `head.html` is successful (`provider = data.provider`). This variable should replace thymeleaf directives that uses `${provider}` passed as model attribute. Since this operation is async, we should somehow observe changes applied to this variable. Basically when `provider` variable is changed, use jQuery to update dom elements where thymeleaf ${provider} is used. A good starting point to achieve this, would be using proxies: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy#manipulating_dom_nodes".

Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-31T09:36:13.845168``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@criske one question: I don;'t understand why we need some special mechanism to observe the variable? On each page load, the ajax call in ``<head>`` will be executed and this variable will be set. Then based on it we just render some elements on the page or not. Or am I missing something? :D

**Comment by amihaiemil** [comment]
@criske btw, if it turns out to be something complicated, better not do it at all (we can also leave it with Thymeleaf if jquery is too complex).

**Comment by criske** [comment]
@amihaiemil yes but just updating this global variable will not update the elements.
For example if we have `var globalProvider = "No provider"` and some `<span class="provider"/>`, just setting on doc ready `$('.provider').text(globalProvider)` would not be enough, cause in the meantime the async call from `<head>` is still going.
so  `ajax().then((data) => globalProvider = data.provider)` will not cause `$('.provider')` to update, it will still show the old value (`No provider`)

To fix this we will have to do something like:
`ajax().then((data) => globalProvider.change(data.provider)` 
and somewhere else on doc ready:
`globalProvider.onChange(value => $('.provider').text(value))`

**Comment by amihaiemil** [comment]
@criske well, if you can do it in a simple manner, then go with it :D If it turns out that it's more complex, better keep with the Model version :D

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
