### ISSUE TITLE
head.html:  Global profile variable.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#347]
Same as global provider, we should have a global js variable `profile` that will be initialized when   `/api/users/self` call in `head.html` is successful. (`globalProfile.change(data)`)
https://github.com/self-xdsd/self-web/blob/a2d3bd04d47c816729140d11776dfad89792360b/src/main/resources/templates/head.html#L50-L55
After that:
- in getProject.js replace  `/api/users/self` call with `globalProfile.onChange(...)`
 https://github.com/self-xdsd/self-web/blob/a2d3bd04d47c816729140d11776dfad89792360b/src/main/resources/public/js/getProject.js#L11-L13 
- in "user.html", remove  thymeleaf directives (`th`) and create a script where, when globalProfile changes, updates "username", "provider", "email" and "providerLink" elements. (also `Model` from `UserController#index` is not needed anymore).

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-03T11:26:16.070327``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike remove

**Comment by charlesmike** [comment]
> @charlesmike remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@charlesmike add

**Comment by charlesmike** [comment]
> @charlesmike add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-03T15:16:14.033087``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
