### ISSUE TITLE
getProject.js: Wrong pm link for when project is on Gitlab.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#350]
Link for pm profile is hardcoded for Github. It should be created based on project provider base url (ex: "gitlab.com").
https://github.com/self-xdsd/self-web/blob/47a240122b2e97c4bf8204383068192e19440282/src/main/resources/public/js/getProject.js#L46-L51

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-04T16:16:40.220681``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
