### ISSUE TITLE
Add Ukraine and Russia to BillinInfo Form

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#355]
Try to add Ukraine and Russia to the BillingInfo formular of the Contributor (PayoutMethod creation).

Ukraine and Russia are not supported by Stripe for businesses (platform accounts), but maybe they allow Connected Accounts to be from these countries.

Then, try to create a PayoutMethod with one of these countries. Stripe should begin an "onboarding flow" and it should ask for your address, picture of your passport etc (in Test, you should have the option to provide mock documents).

**Comment by charlesmike** [comment]
@nmonokov this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-10T15:12:40.160597``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by nmonokov** [comment]
@amihaiemil Sorry, I’m afraid I don’t follow you. Are you suggesting to try to create a Stripe account via self-web application from local machine?

**Comment by amihaiemil** [comment]
@nmonokov yes yes. Modify the front end formular (the country select box) and add/select the option UA (Ukraine). You will also have to add UA to the backend validator (ValidCountryValidator).

Then, try to create the PayoutMethod with UA country, see if it works. I expdct Stripe to throwan exception, but let's try.

And yes, creating a PayoutMethod means creating a kind of Stripe account (called Stripe Connect)  which is connected to the account og Self XDSD in Stripe -- that's how contributors get paid.

When you work with self-web from localhost, everything will be in Test mode, including Stripe.

**Comment by nmonokov** [comment]
@amihaiemil Hey, i asked my friend to help me with paypal thing. So we can stick to using paypal after all.

**Comment by amihaiemil** [comment]
@nmonokov ok, just send me an email with the address :D

**Comment by charlesmike** [comment]
@nmonokov Don't forget to close this ticket before the deadline (2021-02-10T15:12:40). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@nmonokov Looks like you've missed the task deadline (2021-02-10T15:12:40). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@MihaiDejeu this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-20T19:26:40.046319``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike remove

**Comment by charlesmike** [comment]
> @charlesmike remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
