### ISSUE TITLE
Mobile: Move Authenticated Avatar To The Side

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#357]
In this PR https://github.com/self-xdsd/self-web/pull/354/files we centered the login buttons on mobile:

<img width="429" alt="Screenshot 2021-02-06 at 21 29 10" src="https://user-images.githubusercontent.com/6305156/107127974-9ce30580-68c2-11eb-9b1d-51ccc5c84a84.png">

This looks fine but, after login, the Logo and User Avatar are still displayed in a column:

<img width="407" alt="Screenshot 2021-02-06 at 21 30 12" src="https://user-images.githubusercontent.com/6305156/107127984-c13ee200-68c2-11eb-8b51-d9fe3b1568e8.png">

This doesn't look very good. Can we have the login buttons in a column (as it is now) and, after login, have logo and  the user avatar/button in a line, as before? 

<img width="436" alt="Screenshot 2021-02-06 at 21 32 17" src="https://user-images.githubusercontent.com/6305156/107128014-08c56e00-68c3-11eb-8593-b948978c587a.png">

**Comment by charlesmike** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-16T21:35:59.910608``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@Lumi3011 Have a look here. Can you fix it when you have some time, please? :D

**Comment by Lumi3011** [comment]
@amihaiemil Sure, I'll look and see what I can do :D

**Comment by Lumi3011** [comment]
@amihaiemil The only solution I can think of is to verify in js if the user is authenticated and then put the style in js. If I can do that, in which js file can I write this code?

**Comment by amihaiemil** [comment]
@Lumi3011 in the header file there is a JS snippet which calls ``/api/users/self`` to get the authenticated user and show/hide the "unauthenticated" / "authenticated" divs based on the response.

I think that's where you need to look. :D

**Comment by amihaiemil** [comment]
@Lumi3011 also during the ajax call, the logo and loading circle should be in line, not in column, that's a corner case to look out for :D

**Comment by charlesmike** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2021-02-16T21:35:59). You are past the first half of the allowed period.

**Comment by Lumi3011** [comment]
@amihaiemil I resolved this task but sort of 99%. What I did is to verify the width of the screen so I can modify the css. But because I had to do that in js, if you modify the width manually (like in inspect element), the changes will apply only if you refresh the screen so the app can know that the width has changed. This won't be a problem if you enter the site on mobile because it will know from the start the width, but like I said, just with manual change it occurs.
I also found a solution, to add a listener for the width, but I haven't been able to implement it, maybe I did something wrong when I tried, because the code in that js file was a little confusing.
If you can have a look, this is a link with the listener solution : https://css-tricks.com/working-with-javascript-media-queries/

**Comment by amihaiemil** [comment]
@Lumi3011 looks good, thanks! Paid with transaction id 61C73137JP3229523

**Comment by charlesmike** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
