### ISSUE TITLE
Allow Dot Add Contract UserName Validation

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#359]
On the Project Contracts Tab, in the Add Contract formular, let's change the validation to also allow dots in the username. At the moment they are forbidden:

This change has to be done in the backend validator and probably also somewhere in the front-end, if it's present.

<img width="366" alt="Screenshot 2021-02-07 at 10 06 07" src="https://user-images.githubusercontent.com/6305156/107140679-6346e480-692c-11eb-8590-5fb64cffc4b2.png">

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-17T10:08:33.323195``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@fellahi-ali Don't forget to close this ticket before the deadline (2021-02-17T10:08:33). You are past the first half of the allowed period.

**Comment by fellahi-ali** [comment]
@amihaiemil wow, I haven't seen this task till now, sorry :(
I think I have some issue with github app notifications.

**Comment by fellahi-ali** [comment]
@amihaiemil There is a similar problem when activating a repo whose owner's name contains a dot `.`, could I fix it in the scope of this task or report an issue for it?
![gitlab-activate-repo-error](https://user-images.githubusercontent.com/25110612/107770009-105c9b00-6d39-11eb-8fed-d530436177f8.png)

**Comment by amihaiemil** [comment]
@fellahi-ali report a new issue and I will assign it to you.:D 

They are sepparate problems regarding validation of the ContractInput (when registering a new contract) and RepoInput (when activating a repo).

**Comment by amihaiemil** [comment]
@fellahi-ali 

>  I think I have some issue with github app notifications.

Github will automatically mark a Notification as read (it will not appear in Github), when you open the notification e-mail. 
In order to prevent this, you have to disable image-loading in your e-mail client.

When you open a Notification e-mail from Github, it contains an invisible image with an ``onload`` script, which calls Github and then Github will mark the notification as seen... so later, when you open Github, the notification will not appear anymore.

**Comment by amihaiemil** [comment]
paid with transaction id 00B70647H71822519

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
