### ISSUE TITLE
Can't activate a repo if its owner name contain a dot 

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-web#361]
@amihaiemil  Same as for #359 we should allow owners with a name that contains a dot to activate thiers repos.
![activate repo error](https://user-images.githubusercontent.com/25110612/107801517-74468a00-6d60-11eb-8d51-9539864ba1cf.png)

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@fellahi-ali thanks. I'll have a look over your PR, but only tomorrow. I'm away from my laptop now.

It's ok if you leave this ticket for monday, you don't have to work in the weekend :D

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-22T19:40:21.561395``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by fellahi-ali** [comment]
> @fellahi-ali thanks. I'll have a look over your PR, but only tomorrow. I'm away from my laptop now.
> 
> It's ok if you leave this ticket for monday, you don't have to work in the weekend :D 

sure no problem :)

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
