### ISSUE TITLE
Allow Deactivation Of All PaymentMethods

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#371]
At the moment, in the Real Wallet, it's not possible to deactivate the active PaymentMethod (at least one payment method/card needs to be active). Let's change this.

Let's allow deactivation of all payment methods and display a read warning in case all the payment methods are disabled.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-03T18:10:46.732913``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-03-03T18:10:46). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-20T10:47:17.987349``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
