### ISSUE TITLE
Org Grang Access Link Broken

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#378]
The link is broken because of the provider-listener in getOrgRepos.js.

Let's change that listener to simply show/hide the Github Org Access link (GitLab does not not seem to have such a page).

**Comment by zoeself** [comment]
@amihaiemil thank you for reporting this. Unfortunately, @amihaiemil is not a contributor with the required role (DEV), that's why I unassigned them. 

I will assign a contributor to take care of it soon.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-09T18:07:17.818278``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
