### ISSUE TITLE
Badge Link Doesn't Initialize On New Project

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#379]
When a new repo is activated and the details show up after activation, the Markdown/HTML links to the Self XDSD badge are not initalize:

![Screenshot 2021-02-27 at 20 13 22](https://user-images.githubusercontent.com/6305156/109396051-62f0a680-7938-11eb-9caa-38e899409256.png)

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-09T18:14:31.257089``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
