### ISSUE TITLE
Implement 404 and 500 Pages

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#399]
Under the ``templates`` folder, create the ``error`` folder with the files ``404.html`` and ``500.html``. They should include the head, header and footer template, same as the other pages like, for example, badge.html. 

In the center of the page's main content, there should be the corresponding image. 

To test the 404 page, just go to ``http://localhost:8080/images/notfound`` (access to the ``images`` folder is allowed even if not authenticated) or go to ``http://localhost:8080/some/not/gound`` while authenticated.

We don't need a page for 503, that will be an external html page independent of the application.

**Comment by zoeself** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-27T15:42:01.959391``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@Lumi3011 Am vazut imaginile si mi-au placut, le poti folosi pt paginile astea, cand ai timp :D 

De cazul 503 ma ocup eu.

**Comment by zoeself** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2021-03-27T15:42:02). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
