### ISSUE TITLE
Allow Removal Of A Payment Method

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#407]
The user should be able to delete a PaymentMethod from their Real Wallet. The 'Delete' icon should only be visible when the method is inactive (we cannot remove an active PaymentMethod). 

The backend endpoint for this also needs to be implemented. We can use simply ``PaymentMethod.remove()`` ( ``StripePaymentMethod.remove()`` will also remove it from Stripe).

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-31T16:02:21.624968``.

Estimation here is ``90 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@criske Don't forget to close this ticket before the deadline (2021-03-31T16:02:22). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
