### ISSUE TITLE
Empty Fake Wallet Div

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#411]
I deployed the new self-web in Test Environment and I removed the Fake Wallets from the DB manually, for projects which already had a Real Wallet. 

Then, when I reload the page: 

![Screenshot 2021-03-27 at 09 26 24](https://user-images.githubusercontent.com/6305156/112713595-a65e1680-8ede-11eb-8e52-e3c3531345f2.png)

This bug did not occur when I tested the activation of the real wallet (where the fake wallet is deleted automatically). It seems to occur at the initial GET /wallets.

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-06T07:28:27.991876``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
