### ISSUE TITLE
Yellow Warning Visible After First Payment Method Is Added

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#413]
When creating a new Stripe Wallet and adding the first PaymentMethod, the method is successfully added and activated.

However, the yellow warning is still present and the Wallet cannot be activated until you deactivate and activate the PaymentMethod again. 

![Screenshot 2021-03-27 at 18 08 03](https://user-images.githubusercontent.com/6305156/112726749-b9e19f80-8f27-11eb-9570-96e4a7f302b8.png)

In the screenshot above, the yellow message appeared right after adding the first Payment Method and it will not go away unless I deactivate and activate it again,

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-06T16:11:39.714887``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske Can you also fix this when you have some time pls? :D

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
