### ISSUE TITLE
Implement the 'Tasks' Tab On The Project Page

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#416]
On the Project page, we should implement the Tasks tab, where we should display a card with a table containing all the tasks which are in scope (task id, estimation, role, assignee, value). 

Let's start with the front-end, implement the tab and show/hide on click (see other tabs as example). In the beginning, the tab should contain just an empty bootstrap card with an empty table (see how Jquery Datatable is used). 

Then we will implement the backend endpoint later.

It should look something like this:

![Screenshot_2021-03-31 Self XDSD](https://user-images.githubusercontent.com/6305156/113112596-08d25200-9212-11eb-81d0-94153e7bdcd5.png)

**Comment by zoeself** [comment]
@Lumi3011 this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-10T08:04:42.527388``.

Estimation here is ``180 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by Lumi3011** [comment]
Hei @amihaiemil, aparent am o problema cu baza de date, daca ma poti ajuta.
![image](https://user-images.githubusercontent.com/32979820/113502640-3717a080-9536-11eb-85e8-123daee37953.png)

Am incercat sa iau din nou baza de date de aici ( https://github.com/self-xdsd/self-storage/blob/0.0.66/src/test/resources/createDb.sql ) in caz ca se schimbase ceva dar tot am eroarea.

**Comment by amihaiemil** [comment]
@Lumi3011 e bun fisierul sql rulat, dar versiunea e deja veche (0.0.66.). Mai ruleaza-l o data, dar selecteaza ultima versiune, de pe master (in pagina de Github, in dreapta sus pe undeva e un selectbox).

Si nu uita sa inserezi PM-ul, ca sa mearga activarea de proiect :D

**Comment by zoeself** [comment]
@Lumi3011 Don't forget to close this ticket before the deadline (2021-04-10T08:04:43). You are past the first half of the allowed period.

**Comment by Lumi3011** [comment]
@amihaiemil in ce fisier ar trebui sa adaug  Jquery Datatable pentru tabelul de tasks? Am vazut ca nu e ceva separat pentru task-uri, dar in acelasi timp e deja un tabel cu task-uri in getAndAddContracts. Fac un js separat cu getAndAddTasks?

**Comment by amihaiemil** [comment]
@Lumi3011 e putin dezordonat codul, intr-adevar, scuze. Dar sigur trebuie ceva separat.

Ce vezi pe-acolo legat de task-uri este pentru task-urile unui Contract (tab-ul de Contracts, tabelul din stanga jos) sau pagina de Contributor Dashboard, tabelul tot din stanga jos.

E ok daca faci structira de HTML de ``<table>`` vezi cum e la restu, si on-click pe tab-ul de Tasks, dupa ce faci show/hide la tot ce trebuie, zici $("#projectTasksTable").dataTable(), sa il deseneze doar. Restul JS-ului pt fetch si toate cele il facem intr-un task viitor, ca nu e facuta inca partea de backend.

**Comment by Lumi3011** [comment]
@amihaiemil Ok atunci, eu ma uitam pe acolo si cum se face pentru restul js-ului, de-asta intrebam. Am dat push cu ce am facut, sa imi spui daca e ok :D

**Comment by zoeself** [comment]
@Lumi3011 thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
