### ISSUE TITLE
Info Badge After Activating A Repo

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#420]
After activating a Repository for the first time, we should show some kind of info badge saying something like: ``You're almost there. Just give our PM a few minutes to accept the Github invitation, then you'll be all set up.``

This message should appear only in the case of a Github repo (in GitLab we don't have to accept invitations) and only once. After the page is refreshed, it should never be visible again.

The badge should be placed on top of the card body:

![Screenshot 2021-04-12 at 20 13 01](https://user-images.githubusercontent.com/6305156/114434540-cde5fc00-9bcb-11eb-97f5-d86c752364dc.png)

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-22T17:16:09.763975``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-24T12:26:36.150923``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
