### ISSUE TITLE
Don't Display Whole FailReason If Payment Error

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#425]
In the failed payment overlay bubble, do not display the failReason if the Payment failed because of an Error (in this case, chances are that the reason is a long exception message). Furthermore, errored payments should never occur - if they do, we have a problem that we need to fix.

![Screenshot 2021-04-15 at 07 33 02](https://user-images.githubusercontent.com/6305156/114814430-db160d00-9dbc-11eb-9b4c-e784dee1e9ed.png)

Display a generic message instead.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-25T04:33:43.273159``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-04-25T04:33:43). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@criske Can you please take care of this when you have some time? So, if the Payment status is ERROR, don't display the message (because it is most likely an exception). Instead, we should display a generic message: "Something went wrong, please try again.".

Payments with status ERROR should never occur so a generic message is fine. We will make the PM report errored payments, a bit later, and we should fix them when they happen.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-05-01T12:06:36.151248``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
