### ISSUE TITLE
Update to core 81 and storage 70

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#436]
For the JsonResources caching using the e-tag mechanism.

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
