### ISSUE TITLE
Users.java:40 Update the getPublicRepos.js function.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#44]
Update the getPublicRepos.js function to fetch the github/gitlab repos according to the "provider" attribute returned  the from "/api/users/self" endpoint.

https://github.com/self-xdsd/self-web/blob/a671a3fcc811dde8fccb61472f872e69492bb712/src/main/java/com/selfxdsd/selfweb/api/Users.java#L40

@amihaiemil I've added a ":" after todo and broke the puzzle, sorry about that.
https://github.com/self-xdsd/self-web/pull/43#commitcomment-40998512

**Comment by amihaiemil** [comment]
will be done in #48
