### ISSUE TITLE
ProjectsApi.java:44-46: Unify the projects endpoint to...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#61]
The puzzle `58-d7319092` from #58 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/9a284d3506be871de0c887f9187c276f5606ccc4/src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java#L44-L46

The puzzle was created by @amihaiemil on 24-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
paid with transaction id 1G894001BP682134E

**Comment by 0pdd** [comment]
The puzzle `58-d7319092` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
