### ISSUE TITLE
GetOrgRepos.js:15 - Will error with 'undefined' if there are no orgs.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#62]
I'm getting `Uncaught TypeError: Cannot read property 'sort' of undefined`

Solution:
- `api/repositories/orgs` returns an empty array (now is no content).
- or just update `GetOrgRepos.js:15` with:`(repos || []).sort(....)`

**Comment by amihaiemil** [comment]
@criske solution for missing data in REST is usually 204 NO CONTENT, so yes, I think this should be handled client-side :D
