### ISSUE TITLE
ProjectsApi.java:90 Endoint "project" and explicit github provider.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#64]
https://github.com/self-xdsd/self-web/blob/8da9b1ab0d571a92d07f95817668787416cdcb13/src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java#L90
I think we can make this endpoint generic. We can get the provider from `user`.
Also I think we can use `fullName` for path variable istead of `owner + name`. Js looks like it's already use it:
https://github.com/self-xdsd/self-web/blob/8da9b1ab0d571a92d07f95817668787416cdcb13/src/main/resources/public/js/getProject.js#L15

**Comment by amihaiemil** [comment]
@criske The endpoint will be made generic ("unified") in #61 -- it will work for all providers.

As for the path variables, I think it's better to leave them separated, so we don't have to use ``substring`` in the logic :D

**Comment by criske** [comment]
@amihaiemil  Oh, didn't notice there is an issue already opened. You can assign me for that too, if you want :D
