### ISSUE TITLE
ProjectsApi.java:49-51: Let's move the /contracts methods...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#75]
The puzzle `73-21b27e48` from #73 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/583554857ed0d910be62d5158b19a4d16ac39e1e/src/main/java/com/selfxdsd/selfweb/api/ProjectsApi.java#L49-L51

The puzzle was created by @amihaiemil on 04-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I work on this, no bounty needed. it's just a refactor :)

**Comment by 0pdd** [comment]
The puzzle `73-21b27e48` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
