### ISSUE TITLE
Handling "org.jooq.exception.DataAccessException".

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#76]
Right now it's leaking database internals. I think we should have an `@ExceptionHandler` in `BaseApiController` that will forward  with something generic like "_Something went wrong"_.
Here is what is showing in browser when introducing the same project contract twice:
![dataacess_exception_leak](https://user-images.githubusercontent.com/10284893/92257797-7ae1f300-eede-11ea-9cfd-bd9916f1cf7f.png)
I'll take care of it if that's ok.

Edit: or just go with a catch-all `@ResponseStatus` handler for any 500 statuses?

**Comment by amihaiemil** [comment]
@criske well, first of all we should have some validations, to not insert anything twice (we should not let it go until the persistence layer to fail).

Then, yes, we should definitely have appropriate ExceptionHandlers. :D

**Comment by amihaiemil** [comment]
By the way, Github is saying that self-web is more JS than Java now. This is nice, it's as intended.

**Comment by criske** [comment]
> @criske well, first of all we should have some validations, to not insert anything twice (we should not let it go until the persistence layer to fail).
> 
> Then, yes, we should definitely have appropriate ExceptionHandlers. :D

@amihaiemil Actually the insertion at storage layer is handling this pretty well. There is small bug there that won't trigger our ISE: the insert should have `.onDuplicateKeyIgnore()` attached. (I'll open an issue there)

>By the way, Github is saying that self-web is more JS than Java now. This is nice, it's as intended.

That's nice, the language itself not so nice. :D

**Comment by amihaiemil** [comment]
paid with transaction id 0H820053D6552620R
