### ISSUE TITLE
ContractInput 'hourlyRate' field should have @NotBlank contraint too.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-web#77]
https://github.com/self-xdsd/self-web/blob/583554857ed0d910be62d5158b19a4d16ac39e1e/src/main/java/com/selfxdsd/selfweb/api/input/ContractInput.java#L49

Otherwise validation message will be the NumberFormatException
![screencapture-localhost-8080-github-criske-app-portfolio-2020-09-05-09_53_33](https://user-images.githubusercontent.com/10284893/92299800-57f72380-ef5e-11ea-9a9b-badd16552c07.png)

I'll take care of this, no bounty needed.

**Comment by amihaiemil** [comment]
@criske Yes, but there should also be validation on the front-end? Is that missing?

**Comment by criske** [comment]
@amihaiemil The form serialization could sneak an empty string instead of "0.0" when houryRate is empty. Otherwise the proper validation is done on backend.

**Comment by amihaiemil** [comment]
@criske Doesn't matter, we should always have front-end validation as well :D 
I'll open another issue.

**Comment by criske** [comment]
@amihaiemil Ok ,if that's the case, then I think you could reject this PR. I'll take care of frontend validation.

**Comment by amihaiemil** [comment]
@criske that's already merged, let's just move to the new ticket
