### ISSUE TITLE
AddContract form should have front-end validation as well.

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-web#80]
On the Project page -> Contracts tab. The add-contract form needs front-end validation too.

**Comment by amihaiemil** [comment]
@criske btw, you can look how I've done it in the Add-PM formular. You won't be able to see that page when you run the app, but look into its code. I used the ``required`` class :D

**Comment by criske** [comment]
@amihaiemil since we're doing full validation on front-end, wouldn't be better to use https://jqueryvalidation.org/ plugin?

**Comment by amihaiemil** [comment]
@criske you can try it, yes. I remember I tried using it but it was a bit frustrating so I just did it myself.

**Comment by amihaiemil** [comment]
paid with transaction id 1VL98299EC597612F
