### ISSUE TITLE
ContractsApi.java:47-48: Start implementing...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#86]
The puzzle `84-8b067e21` from #84 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/6df6adbde4669cad7dc0749b75ae56f829664a73/src/main/java/com/selfxdsd/selfweb/api/ContractsApi.java#L47-L48

The puzzle was created by cristianpela on 05-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this.

**Comment by criske** [comment]
I'll wait until `Self` has access to `contributors()`.

**Comment by amihaiemil** [comment]
waiting for https://github.com/self-xdsd/self-core/issues/521
