### ISSUE TITLE
JsonContract.java:15-20: Remove the project attribute...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-web#92]
The puzzle `89-ce51b155` from #89 has to be resolved: 

https://github.com/self-xdsd/self-web/blob/2c37810ad017a7ba277bbede84d74a238b518eaf/src/main/java/com/selfxdsd/selfweb/api/output/JsonContract.java#L15-L20

The puzzle was created by @amihaiemil on 11-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske Can you pls take care of this? It's really easy, just remove the line

``.add("project", new JsonProject(contract.project()))`` and also remove any jquery/front-end stuff which does something with the project attribute from the response.

**Comment by criske** [comment]
@amihaiemil sure

**Comment by 0pdd** [comment]
The puzzle `89-ce51b155` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@criske thanks for fixing it! Paid with transaction id 8EC668309U587850A
